version: "3.9"
services:
   db:
      image: postgres:16
      environment:
        POSTGRES_DB: "tablo"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "admin"
      ports:
        - "5432:5432"
      network_mode: host

   tennis:
      build: .
      ports:
        - "8001:8001"
      network_mode: host
      depends_on:
        db:
          condition: service_started
      restart: always

