version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "tablo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5433:5432"
      