"""empty message

Revision ID: 3468e40cc599
Revises: e044b891fd8a
Create Date: 2024-09-22 01:20:22.941001

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3468e40cc599'
down_revision: Union[str, None] = 'e044b891fd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Matches', sa.Column('player1', sa.Integer(), nullable=True))
    op.add_column('Matches', sa.Column('player2', sa.Integer(), nullable=True))
    op.add_column('Matches', sa.Column('winner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Matches', 'Players', ['player2'], ['id'])
    op.create_foreign_key(None, 'Matches', 'Players', ['player1'], ['id'])
    op.create_foreign_key(None, 'Matches', 'Players', ['winner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Matches', type_='foreignkey')
    op.drop_constraint(None, 'Matches', type_='foreignkey')
    op.drop_constraint(None, 'Matches', type_='foreignkey')
    op.drop_column('Matches', 'winner')
    op.drop_column('Matches', 'player2')
    op.drop_column('Matches', 'player1')
    # ### end Alembic commands ###
