"""empty message

Revision ID: 87d7984e6225
Revises: 5a5cedfdfa6c
Create Date: 2024-09-22 00:54:08.142139

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '87d7984e6225'
down_revision: Union[str, None] = '5a5cedfdfa6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
