"""empty message

Revision ID: 97ba388c0add
Revises: 386fa19e6d37
Create Date: 2024-09-14 02:42:37.356813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ba388c0add'
down_revision: Union[str, None] = '386fa19e6d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Matches_uuid', table_name='Matches')
    op.create_unique_constraint(None, 'Matches', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Matches', type_='unique')
    op.create_index('ix_Matches_uuid', 'Matches', ['uuid'], unique=True)
    # ### end Alembic commands ###
