"""empty message

Revision ID: af82d65bbc06
Revises: 92e194992939
Create Date: 2024-09-22 01:25:30.345335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af82d65bbc06'
down_revision: Union[str, None] = '92e194992939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Matches')
    op.drop_index('ix_Players_name', table_name='Players')
    op.drop_table('Players')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Players',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Players_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Players_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_Players_name', 'Players', ['name'], unique=True)
    op.create_table('Matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('player1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('winner', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player1'], ['Players.id'], name='Matches_player1_fkey'),
    sa.ForeignKeyConstraint(['player2'], ['Players.id'], name='Matches_player2_fkey'),
    sa.ForeignKeyConstraint(['winner'], ['Players.id'], name='Matches_winner_fkey'),
    sa.PrimaryKeyConstraint('id', name='Matches_pkey'),
    sa.UniqueConstraint('uuid', name='Matches_uuid_key')
    )
    # ### end Alembic commands ###
