"""empty message

Revision ID: e044b891fd8a
Revises: 05bebae4e0f0
Create Date: 2024-09-22 01:18:04.786691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e044b891fd8a'
down_revision: Union[str, None] = '05bebae4e0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Matches_player1_id_fkey', 'Matches', type_='foreignkey')
    op.drop_constraint('Matches_player2_id_fkey', 'Matches', type_='foreignkey')
    op.drop_constraint('Matches_winner_fkey', 'Matches', type_='foreignkey')
    op.drop_column('Matches', 'player1_id')
    op.drop_column('Matches', 'winner')
    op.drop_column('Matches', 'player2_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Matches', sa.Column('player2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Matches', sa.Column('winner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Matches', sa.Column('player1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Matches_winner_fkey', 'Matches', 'Players', ['winner'], ['id'])
    op.create_foreign_key('Matches_player2_id_fkey', 'Matches', 'Players', ['player2_id'], ['id'])
    op.create_foreign_key('Matches_player1_id_fkey', 'Matches', 'Players', ['player1_id'], ['id'])
    # ### end Alembic commands ###
